//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGV_Mark6 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    public sealed partial class AGV_Statuses_On_App_Load : global::System.Configuration.ApplicationSettingsBase {
        
        private static AGV_Statuses_On_App_Load defaultInstance = ((AGV_Statuses_On_App_Load)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AGV_Statuses_On_App_Load())));
        
        public static AGV_Statuses_On_App_Load Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Загруженность:Пустая")]
        public string OnAppStart_loadStatus {
            get {
                return ((string)(this["OnAppStart_loadStatus"]));
            }
            set {
                this["OnAppStart_loadStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Склад")]
        public string OnAppStart_LastBase {
            get {
                return ((string)(this["OnAppStart_LastBase"]));
            }
            set {
                this["OnAppStart_LastBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnAppStart_TaskCanceled {
            get {
                return ((bool)(this["OnAppStart_TaskCanceled"]));
            }
            set {
                this["OnAppStart_TaskCanceled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnAppStart_TransitionExit {
            get {
                return ((bool)(this["OnAppStart_TransitionExit"]));
            }
            set {
                this["OnAppStart_TransitionExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnAppStart_CurrentTaskSteps {
            get {
                return ((string)(this["OnAppStart_CurrentTaskSteps"]));
            }
            set {
                this["OnAppStart_CurrentTaskSteps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnAppStart_TransitionMissCount {
            get {
                return ((string)(this["OnAppStart_TransitionMissCount"]));
            }
            set {
                this["OnAppStart_TransitionMissCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnAppStart_AGV_Quest {
            get {
                return ((string)(this["OnAppStart_AGV_Quest"]));
            }
            set {
                this["OnAppStart_AGV_Quest"] = value;
            }
        }
    }
}
